# Generated by Django 3.1.7 on 2021-02-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='author',
            field=models.CharField(default='Nonexistent.', max_length=300, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='book',
            field=models.CharField(default='Nonexistent.', max_length=300, verbose_name='Book'),
        ),
    ]
