# Generated by Django 3.1.7 on 2021-02-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_v1', '0002_auto_20210227_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='quote',
            field=models.TextField(unique=True, verbose_name='Literary Quote'),
        ),
    ]
