# Generated by Django 3.1.7 on 2021-02-28 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_v1', '0003_auto_20210227_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('language_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='quotes',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes_v1.languages'),
        ),
    ]
