# Generated by Django 3.1.7 on 2021-02-28 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_v1', '0004_auto_20210227_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languages',
            options={'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
    ]
