# Generated by Django 3.1.7 on 2021-02-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_v1', '0005_auto_20210227_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='language',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='language_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
